[article]
title = """
文章的标题填写在这里
"""

authors_simple = "韩信, 白起"       # 纯文本最简形式来标明作者

abstract = """
Abstract is the primary public description of the article; it is not pumping elephant.

Use an empty line to separate multiple paragraphs.
"""






# 一作
[[author]]
full_name = "韩信"
index_name = "Han, X."
email = "user1@example.com"
orcid = "0000-0002-1825-0097"   ### 无则留空
corresponding = true            ### 是通讯作者
affiliations = [ 1, 2 ]         ### 依序号引用所在机构

# 二作
[[author]]
full_name = "白起"
index_name = "Bai, Q."
email = "user2@example.com"
orcid = "0000-0003-4418-1234"   ### 无则留空
corresponding = false           ### 不是通讯作者
affiliations = [ 2 ]            ### 依序号引用所在机构



# 研究机构，可以没有
[affiliations.1]
organization = "同福客栈"
city = "七侠镇"
country = "XXX"
ror = "https://ror.org/00f54p054"

[affiliations.2]
organization = "麦篝乐队"
city = "夷陵"
country = "XXX"
ror = "https://ror.org/012345678"

